# <b>Exploratory Data Analysis</b>
Here we do some analysis on the data to understand how big the data is, what it looks like and perhaps discover where the errors occur.

## Setup: Imports And Loading Data

In [108]:
import pandas as pd
from pathlib import Path

# path to "raw" data, data from company
dataRaw = Path("../data/raw")

# load all data files
apc = pd.read_csv(dataRaw/'apc_report.csv')
matched_stops = pd.read_csv(dataRaw/'matched_stops.csv', encoding_errors='ignore')
matched_tips = pd.read_csv(dataRaw/'matched_trips.csv')
thoreb = pd.read_csv(dataRaw/'thoreb.csv', encoding_errors='ignore')

C:\Users\Abdullah\AppData\Local\Temp\ipykernel_18188\2822643783.py:11: DtypeWarning: Columns (0: block, 1: diff, 2: journey, 3: line, 4: noJourney, 5: pointID, 6: stoptime, 7: vehicle) have mixed types. Specify dtype option on import or set low_memory=False.
  thoreb = pd.read_csv(dataRaw/'thoreb.csv', encoding_errors='ignore')

## Section 1: APC

Basic information about the file

In [147]:
# shape pf the data, (rows, columns)
print("Shape:", apc.shape)

# how many rows is there
print("Number of rows:", apc.shape[0])

# how many columns is there
print("Number of columns:", apc.shape[1])

Shape: (296924, 27)
Number of rows: 296924
Number of columns: 27

Column names in the data

In [ ]:
# List column names
apc.columns.tolist()

['fileName',
 'stationName',
 'stationCode',
 'vehicleCode',
 'arrival',
 'departure',
 'boardings',
 'alightings',
 'latitude',
 'longitude',
 'gpsDeviation',
 'operatorCode',
 'isGpsMapped',
 'wheelchairRampAccessCount',
 'isBicycleRackAccessed',
 'area',
 'netstop_latitude',
 'netstop_longitude',
 'pismInformation',
 'boardings_adults',
 'alightings_adults',
 'boardings_children',
 'alightings_children',
 'boardings_wheelchair',
 'alightings_wheelchair',
 'boardings_pram',
 'alightings_pram']

An overview of the data, a few lines from the beginning and a few from the end

In [175]:
#apc.head(5)
#apc.tail(5)
apc

,fileName,stationName,stationCode,vehicleCode,arrival,departure,boardings,alightings,latitude,longitude,...,netstop_longitude,pismInformation,boardings_adults,alightings_adults,boardings_children,alightings_children,boardings_wheelchair,alightings_wheelchair,boardings_pram,alightings_pram
0,NOBINA_3000_20241231_174946_vdv457.raw.gz,NaN,NaN,3000,1/1/2025 0:07,1/1/2025 0:07,0,0,57.111225,12.289127,...,NaN,"pointCode:6555,block:5512,trip:668,tripType:PR...",0,0,0,0,0,0,0,0
1,NOBINA_3000_20241231_174946_vdv457.raw.gz,NaN,NaN,3000,1/1/2025 0:08,1/1/2025 0:08,0,0,57.111214,12.295943,...,NaN,"pointCode:6656,block:5512,trip:668,tripType:PR...",0,0,0,0,0,0,0,0
2,NOBINA_3000_20241231_174946_vdv457.raw.gz,NaN,NaN,3000,1/1/2025 0:09,1/1/2025 0:09,0,0,57.111584,12.301238,...,NaN,"pointCode:6655,block:5512,trip:668,tripType:PR...",0,0,0,0,0,0,0,0
3,NOBINA_3000_20241231_174946_vdv457.raw.gz,NaN,NaN,3000,1/1/2025 0:10,1/1/2025 0:10,0,0,57.111076,12.297543,...,NaN,"pointCode:6656,block:5512,trip:669,tripType:PR...",0,0,0,0,0,0,0,0
4,NOBINA_3000_20241231_174946_vdv457.raw.gz,NaN,NaN,3000,1/1/2025 0:10,1/1/2025 0:11,0,0,57.111470,12.292072,...,NaN,"pointCode:6555,block:5512,trip:669,tripType:PR...",0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296919,Vaestbo_Taxi_9003_20250107_051551_vdv457.raw.gz,NaN,NaN,9003,7/1/2025 19:39,7/1/2025 19:39,0,0,57.007656,13.241302,...,NaN,"pointCode:4511,block:4173,trip:19,tripType:PRO...",0,0,0,0,0,0,0,0
296920,Vaestbo_Taxi_9003_20250107_051551_vdv457.raw.gz,NaN,NaN,9003,7/1/2025 19:40,7/1/2025 19:40,0,0,57.004128,13.240287,...,NaN,"pointCode:4512,block:4173,trip:19,tripType:PRO...",0,0,0,0,0,0,0,0
296921,Vaestbo_Taxi_9003_20250107_051551_vdv457.raw.gz,NaN,NaN,9003,7/1/2025 19:40,7/1/2025 19:41,0,0,57.001217,13.241087,...,NaN,"pointCode:4502,block:4173,trip:19,tripType:PRO...",0,0,0,0,0,0,0,0
296922,Vaestbo_Taxi_9003_20250107_051551_vdv457.raw.gz,NaN,NaN,9003,7/1/2025 19:41,7/1/2025 19:41,0,0,56.999330,13.238167,...,NaN,"pointCode:4500,block:4173,trip:19,tripType:PRO...",0,0,0,0,0,0,0,0
296923,Vaestbo_Taxi_9004_20250107_060006_vdv457.raw.gz,NaN,NaN,9004,7/1/2025 6:00,7/1/2025 6:00,0,0,0.000000,0.000000,...,NaN,NaN,0,0,0,0,0,0,0,0

Information about the data, data types & missing values

In [171]:
apc.info()

<class 'pandas.DataFrame'>
RangeIndex: 296924 entries, 0 to 296923
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   fileName                   296924 non-null  str
 1   stationName                0 non-null       float64
 2   stationCode                0 non-null       float64
 3   vehicleCode                296924 non-null  int64
 4   arrival                    296924 non-null  str
 5   departure                  296924 non-null  str
 6   boardings                  296924 non-null  int64
 7   alightings                 296924 non-null  int64
 8   latitude                   296924 non-null  float64
 9   longitude                  296924 non-null  float64
 10  gpsDeviation               296924 non-null  str
 11  operatorCode               296924 non-null  str
 12  isGpsMapped                296924 non-null  bool
 13  wheelchairRampAccessCount  296924 non-null  int64
 14  isBicycleRackAccessed      296924 non-null  bool
 15  area                       0 non-null       float64
 16  netstop_latitude           0 non-null       float64
 17  netstop_longitude          0 non-null       float64
 18  pismInformation            296068 non-null  str
 19  boardings_adults           296924 non-null  int64
 20  alightings_adults          296924 non-null  int64
 21  boardings_children         296924 non-null  int64
 22  alightings_children        296924 non-null  int64
 23  boardings_wheelchair       296924 non-null  int64
 24  alightings_wheelchair      296924 non-null  int64
 25  boardings_pram             296924 non-null  int64
 26  alightings_pram            296924 non-null  int64
dtypes: bool(2), float64(7), int64(12), str(6)
memory usage: 57.2 MB

<h3>Missing values:</h1>

Number of nulls per column

In [183]:
apc.isnull().sum()

fileName                          0
stationName                  296924
stationCode                  296924
vehicleCode                       0
arrival                           0
departure                         0
boardings                         0
alightings                        0
latitude                          0
longitude                         0
gpsDeviation                      0
operatorCode                      0
isGpsMapped                       0
wheelchairRampAccessCount         0
isBicycleRackAccessed             0
area                         296924
netstop_latitude             296924
netstop_longitude            296924
pismInformation                 856
boardings_adults                  0
alightings_adults                 0
boardings_children                0
alightings_children               0
boardings_wheelchair              0
alightings_wheelchair             0
boardings_pram                    0
alightings_pram                   0
dtype: int64

Description of the data

In [195]:
apc.describe()

,stationName,stationCode,vehicleCode,boardings,alightings,latitude,longitude,wheelchairRampAccessCount,area,netstop_latitude,netstop_longitude,boardings_adults,alightings_adults,boardings_children,alightings_children,boardings_wheelchair,alightings_wheelchair,boardings_pram,alightings_pram
count,0.0,0.0,296924.000000,296924.000000,296924.000000,296924.000000,296924.000000,296924.0,0.0,0.0,0.0,296924.000000,296924.000000,296924.000000,296924.000000,296924.000000,296924.000000,296924.000000,296924.000000
mean,NaN,NaN,4309.222949,0.349531,0.342401,56.260770,12.572344,0.0,NaN,NaN,NaN,0.342815,0.333308,0.006638,0.009006,0.000010,0.000017,0.000081,0.000084
std,NaN,NaN,1022.862423,1.203051,1.134900,5.632180,1.288397,0.0,NaN,NaN,NaN,1.173637,1.101985,0.126639,0.125759,0.003179,0.004104,0.008990,0.009176
min,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,4211.000000,0.000000,0.000000,56.668266,12.454455,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,4245.000000,0.000000,0.000000,56.696968,12.808614,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,4283.000000,0.000000,0.000000,57.028976,12.890022,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,9004.000000,64.000000,61.000000,57.364060,16.145123,0.0,NaN,NaN,NaN,64.000000,61.000000,20.000000,10.000000,1.000000,1.000000,1.000000,1.000000

Checking how many busses we have in the apc data, and also the earliest and latest trip.

In [203]:
print("Unique busses:", apc['vehicleCode'].nunique())
print("Earliest arrival:", apc['arrival'].min())
print("Latest arrival:", apc['arrival'].max())

Unique busses: 174
Earliest arrival: 1/1/2025 0:00
Latest arrival: 7/1/2025 9:59

In [202]:
#print(apc[['stationCode', 'stationName', 'arrival', 'departure', 'boardings', 'alightings', 'vehicleCode']].isna().sum())

## Section 2: Matched Stops

## Section 3: Matched Trips

## Section 4: Thoreb